package Util;

public enum MenuOption {
    MAIN_MENU,
    STUDENT_MAIN_MENU,
    STUDENT_REGISTER_MENU,
    STUDENT_INQUIRE_MENU,
    STUDENT_CHANGE_MENU,
    STUDENT_DELETE_MENU,
    SCORE_MAIN_MENU,
    SCORE_REGISTER_MENU,
    SCORE_INQUIRE_MENU,
    SCORE_CHANGE_MENU,
}
