package Util.Options;

public enum StudentInquireMenuOption {
    STUDENT_INQUIRE_MENU_OPTION_ERROR,
    STUDENT_INQUIRE_MENU_OPTION_ID,
    STUDENT_INQUIRE_MENU_OPTION_STATUS,
    STUDENT_INQUIRE_MENU_OPTION_BACK
}
