package util.printMenu;

public enum MenuOption {
    MAIN_MENU,
    STUDENT_MAIN_MENU,
    STUDENT_REGISTER_MENU,
    STUDENT_REGISTER_HELPER_MENU,
    STUDENT_INQUIRE_MENU,
    STUDENT_INQUIRE_HELPER_ALL_MENU,
    STUDENT_INQUIRE_HELPER_ID_MENU,
    STUDENT_INQUIRE_HELPER_STATUS_MENU,
    STUDENT_CHANGE_MENU,
    STUDENT_CHANGE_HELPER_MENU,
    STUDENT_DELETE_MENU,
    STUDENT_DELETE_HELPER_MENU,
    SCORE_MAIN_MENU,
    SCORE_REGISTER_MENU,
    SCORE_REGISTER_HELPER_MENU,
    SCORE_INQUIRE_MENU,
    SCORE_INQUIRE_HELPER_ID_MENU,
    SCORE_INQUIRE_HELPER_STATUS_MENU,
    SCORE_CHANGE_MENU,
    SCORE_CHANGE_HELPER_MENU,
    INPUT_ERROR_MENU
}
